### ISSUE TITLE
Sorting doesn't work as expected

### ISSUE THREAD

**Issue by 5ouma** [blacktop/lporg#17]
It runs almost correctly, but third-party apps can't step into pre-installed apps.

> Apple apps and the `Other` folder might have a strong power to line up ahead.

```shell
# Expected
• page number: 1
      • found app                 title=App Store
      • found app                 title=Safari
      • found app                 title=Google Chrome
      • found app                 title=Mail

# And more…
```

```shell
# Actual
• page number: 1
      • found app                 title=App Store
      • found app                 title=Safari
      • found app                 title=Mail

# And more…
      • found app                 title=Google Chrome

# And more…
```

on macOS 12.6.2 and Intel

**Comment by vfl97** [comment]
Worked fine for me. Great coding, thanks devs!

(Altho it didn't save the order of the apps in the "others" folder, I put terminal & activity monitor in the 1st & 2nd place in that folder)

**Comment by 5ouma** [comment]
This issue is still happening…
`Version: 20.4.21, BuildTime: 2023-09-04T17:28:18Z`

**Comment by blacktop** [comment]
I think there is something 'special' about the Other folder where Apple treats it differently than other folders? https://github.com/blacktop/lporg/issues/31#issuecomment-1705931818

**Comment by 5ouma** [comment]
I think the default order can't be changed.

```yml
items:
  - App Store
  - Safari
  - Mail
  - Contacts
  - Calendar
  - Reminders
  - Notes
  - FaceTime
  - Messages
  - Maps
  - Find My
  - Photo Booth
  - Photos
  - Preview
  - Music
  - Podcasts
  - TV
  - Voice Memos
  - iMovie
  - Stocks
  - Books
  - Dictionary
  - Calculator
  - Home
  - Siri
  - Mission Control
  - System Preferences
  - folder: Other
    pages:
      - number: 1
        items:
          - Shortcuts
          - QuickTime Player
          - TextEdit
          - Grapher
          - Time Machine
          - Font Book
          - Chess
          - Stickies
          - Image Capture
          - VoiceOver Utility
          - AirPort Utility
          - Migration Assistant
          - Terminal
          - Activity Monitor
          - Console
          - Keychain Access
          - System Information
          - Automator
          - Script Editor
          - Disk Utility
          - Boot Camp Assistant
          - Digital Color Meter
          - ColorSync Utility
          - Screenshot
          - Bluetooth File Exchange
          - Audio MIDI Setup
  - Xcode
```
