### ISSUE TITLE
The problem with the sorting

### ISSUE THREAD

**Issue by sarukomine** [blacktop/lporg#22]
There seems to be a problem with the sorting, because no matter what I put `Google Chrome` and `Firefox` after `Safari`, they (non-Apple apps) always come after Apple apps... I don't know if it's on purpose or a problem that should be fixed. Anyway, sorting is not what I want...

And I wanted to put `Google Chrome` and `Firefox` after `Safari`... Any ways to make it happen?

There's another "not-so-big" problem, when I load the YAML file, it always says:

```
(/Users/blacktop/Developer/Github/blacktop/lporg/database/database.go:370) 
[2023-02-15 22:25:08]  no such table: widgets
```

```yaml
apps:
  pages:
  - number: 1
    items:
    - Safari
    - Google Chrome
    - Firefox
    - Mail
    - Calendar
    - Reminders
    - Notes
    - FaceTime
    - Messages
    - Maps
    - Weather
    - Clock
    - Calculator
    - Visual Studio Code
    - Signal
    - 1Password
    - Couleurs
    - Figma
    - Sequel Ace
    - Obsidian
    - Magnet
    - DevUtils
    - PHP Monitor
    - WhatsApp
    - Fork
    - Discord
    - The Unarchiver
    - Binance
    - Postman
    - Usage
    - JetBrains Toolbox
    - Mos
    - CheatSheet
    - Raycast
    - iTerm
    - Music
    - App Store
    - System Settings
    - folder: Other
      pages:
      - number: 1
        items:
        - Shortcuts
        - QuickTime Player
        - TextEdit
        - Grapher
        - Time Machine
        - Font Book
        - Mission Control
        - Chess
        - Stickies
        - Image Capture
        - VoiceOver Utility
        - AirPort Utility
        - Migration Assistant
        - Terminal
        - Activity Monitor
        - Console
        - Keychain Access
        - System Information
        - Automator
        - Script Editor
        - Disk Utility
        - Digital Color Meter
        - ColorSync Utility
        - Screenshot
        - Bluetooth File Exchange
        - Audio MIDI Setup
        - Contacts
        - Photo Booth
        - Preview
        - Podcasts
        - TV
        - Find My
        - Photos
        - Voice Memos
        - Stocks
        - Books
        - Dictionary
        - Freeform
        - Home
        - Siri
widgets:
  pages: []
dock_items:
- ============
desktop: {}
```

Oh these problems happen on macOS 13.2 with Apple M2 btw.
