### ISSUE TITLE
Add YAML config flag to hide a specific folder 

### ISSUE THREAD

**Issue by duraki** [blacktop/lporg#30]
Something like would be a good addition (note the `hidden` flag):

```yml
    - folder: Miscellaneous
      hidden: true
      pages:
      - number: 1
        items:
        - Assistant
        - Designer
        - IDLE
        - Linguist
        - Python Launcher
        - Linguist
        - pixeltool
        - qdbusviewer
        - qml
        - qwingraph
        - TestFlight
```

This way, we can stuff rarely used apps in a specific folder that will be hidden from the launchpad view.
