### ISSUE TITLE
Cannot save confg

### ISSUE THREAD

**Issue by silver886** [blacktop/lporg#31]
When run this command, `lporg save -V`, it can parse launchpad and dashboard pages.
However, it encounter error during interating over dock apps.

```
   • Saving launchpad settings
   • SAVING LAUNCHPAD DATABASE
      • found launchpad database  database=/var/folders/_y/n7114yk15ll_0yps6s3j_v140000gn/0/com.apple.dock.launchpad/db/db
   • collecting launchpad/dashboard pages
   • interating over launchpad pages
   • page number: 1
      • found app                 title=App Store
      • found app                 title=Safari
      • found app                 title=Mail
      ...
      ...
      ...
   • interating over dashboard pages
   • interating over dock apps
Error: unable to load dock plist: plist: type mismatch: tried to decode plist type `integer' into value of type `float64'
Usage:
  lporg save [flags]

Flags:
  -h, --help   help for save

Global Flags:
  -c, --config string   config file (default is $HOME/.lporg.yaml)
      --icloud          iCloud config
  -V, --verbose         verbose output
```

macOS: 12.6.8 (21G725)
lporg: 20.4.11

**Comment by 5ouma** [comment]
I got the same error with the same versions.

**Comment by blacktop** [comment]
try with latest release please

**Comment by 5ouma** [comment]
The error has been fixed, but the unknown error occurred with no errors.

**Comment by blacktop** [comment]
You might have to download the latest release. I released MANY times yesterday

**Comment by silver886** [comment]
That's a bit weird.

There is no error in the log, but the exit code is non-zero.

```
> lporg save -V --config ./launchpad.yaml
   • using config file: /Users/silver886/launchpad.yaml
   • Saving launchpad settings
   • SAVING LAUNCHPAD DATABASE
      • found launchpad database  database=/var/folders/_y/n7114yk15ll_0yps6s3j_v140000gn/0/com.apple.dock.launchpad/db/db

> echo $?
1
```

**Comment by blacktop** [comment]
My apologies, I've changed too many things all at the same time.  Please try again with the latest version

**Comment by silver886** [comment]
This error code is more straight forward.

```
> lporg version
Version: 20.4.20, BuildTime: 2023-09-04T16:02:00Z

> lporg save -V --config ./launchpad.yaml
   • using config file: /Users/silver886/launchpad.yaml
   • Saving launchpad settings
   • SAVING LAUNCHPAD DATABASE
      • found launchpad database  database=/var/folders/_y/n7114yk15ll_0yps6s3j_v140000gn/0/com.apple.dock.launchpad/db/db
   ⨯ Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

```

It seems like it will need either different build for amd64 and arm64, or include dependency in https://github.com/blacktop/homebrew-tap/blob/master/Formula/ipsw.rb.

**Comment by blacktop** [comment]
@silver886 I just switched to a CGO-less sqlite implementation - https://github.com/blacktop/lporg/releases/tag/v20.4.21

**Comment by silver886** [comment]
Yeah, this version can be executed without error.
However, the `dock_items` appears with some apps where my Dock is empty without any pinned apps.

```yaml
dock_items:
    apps:
        - /System/Applications/Launchpad.app
        - /Applications/Safari.app
        - /System/Applications/Messages.app
        - /System/Applications/Mail.app
        - /System/Applications/Maps.app
        - /System/Applications/Photos.app
        - /System/Applications/FaceTime.app
        - /System/Applications/Calendar.app
        - /System/Applications/Contacts.app
        - /System/Applications/Reminders.app
        - /System/Applications/Notes.app
        - /System/Applications/TV.app
        - /System/Applications/Music.app
        - /System/Applications/Podcasts.app
        - /System/Applications/News.app
        - /Applications/Keynote.app
        - /Applications/Numbers.app
        - /Applications/Pages.app
        - /System/Applications/App Store.app
        - /System/Applications/System Preferences.app
    others:
        - view: 1
          sort: 2
```

Also, when loading the config file, there will be an empty folder named `Other` be created even if there is no such entry in the configuration.

If I add the empty folder into config file, it loads successfully but there is an error during saving.

```yaml
apps:
  pages:
    - number: 1
      items:
        - folder: Built-in
          pages:
            - number: 1
              items:
                - App Store
...
...
...
        - folder: Other
```

```shellsession
> lporg load --no-backup --yes --config ./launchpad.yaml

                                          '.:/+ooossoo+/:-'
                                     ':+ydNMMMMMMMMMMMMMMMNmyo:'
                                   '.--.''.:ohNMMMMMMMMNho:.''..'
                                        -o+.  ':sNMMms-'  .--
                                 '+o     .mNo    '::'   :dNh'    '+-
                                :mMo      dMM-         .NMMs      hNs
                               -NMMNs:--/hMMM+         .MMMNo-''-sMMMs
                          -'   sMMMMMMNNMMMMM:          hMMMMNNNNMMMMN
                         -y    /MMMMMMMMMMMNs           .mMMMMMMMMMMMd     :
                        .mN.    oNMMMMMMMms-             .yNMMMMMMMNy.    -N:
                        hMMm+'   ./syys+-'    -//   ':/-   ./syyys/.    'oNMm'
                       /MMMMMms:.              '.    '''             ./ymMMMMs
                       mMMMMMMMMNo                 '               'sNMMMMMMMN.
                      -MMMMMMMMN+'             :shmmmh+.            'oNMMMMMMMo
                      /MMMMMMMd-             :dds+///sdm/             :mMMMMMMm
                      sMMMMMMd.             :m+'      ':hs'            -mMMMMMM+
                    .hMMMMMMM-             :h:'         'oh.            /MMMMMMN/
                   /mMMMMMMMN'           ./+' .://:::::.  /d/           .MMMMMMMN/
                 'sMMMMMMMMMM/       '.-:-'     '....'     .so-'        oMMMMMMMMN:
                .hMMMMMMMMMMMNs-'     ''                     '--     '-yNMMMMMMMMMN-
               -dMMMMMMMMMMMMMMNs'                                  'yNMMMMMMMMMMMMm.
              -mMMMMMMMMMMMMMMNo'                                    'sMMMMMMMMMMMMMd'
             :NMMMMMMMMMMMMMMm:                                        /NMMMMMMMMMMMMy
            -NMMMMMMMMMMMMMMd.                                        ' -mMMMMMMMMMMMMo
           .mMMMMMMMMMMMMMMd-/o'                                      .o::mMMMMMMMMMMMN/
          'dMMMMMMMMMMMMMMMhmm.                                        -mdhMMMMMMMMMMMMm.
          yMMMMMMMMMMMMMMMMMN-                                          :NMMMMMMMMMMMMMMh
         /MMMMMMMMMMMMMMMMMN:                                            +MMMMMMMMMMMMMMM+
        'mMMMMMMMMMMMMMMMMMo                                              sMMMMMMMMMMMMMMN.
        oMMMMMMMMMMMMMMMMMh                                               'dMMMMMMMMMMMMMMy
       'mMMMMMMMMMMMMMMMMN.                                                :MMMMMMMMMMMMMMM-
       :MMMMMMMMMMMMMMMMMo                                                  yMMMMMMMMMMMMMMy
       sMMMMMMMMMMMMMMMMN'                                                  -MMMMMMMMMMMMMMN'
       dMMMMMMMMMMMMMMMMh                                                    mMMMMMMMMMMMMMM-
       mMMMMMMMMMMMMMMMMo                                                    yMMMMMMMMMMMMMM-
       mMMMMMMMMMMMMMMMMo                                                    sMMMMMMMMMMMMMM.
       hMMMMMMMMMMMMMMMMs                                                    hMMMMMMMMMMMMMN
       oMMMMMMMMMMMMMMMMy                                                    dMMMMMMMMMMMMMy
       .MMMMMMMMMMMMMMMMd                                                    NMMMMMMMMMMMMM-
        yMMMMMMMMMMMMMMMM'                                                  .MMMMMMMMMMMMMh
        .NMMMMMMMMMMMMMMM/                                                  oMMMMMMMMMMMMN-
         :NMMMMMMMMMMMMMMh                                                  mMMMMMMMMMMMMo
          /NMMMMMMMMMMMMMM-                                                /MMMMMMMMMMMMd'
           :NMMMMMMMMMMMMMh                                               'mMMMMMMMMMMMm.
            .hMMMMMMMMMMMMM/                                              oMMMMMMMMMMMN-
              +mMMMMMMMMMMMN-                                            :MMMMMMMMMMMm-
               'oNMMMMMMMMMMm.                                          -NMMMMMMMMMMd-
                 .omNmh+:hNMMm-                                        :NNsmMMMMMMMy'
                   '.     -smMN+                                     'oNh- 'sNMMNh:
                            ':yNh-                                  -hh:     .:-'
                               ':o/'                              '/+.
                                   '                              '


   • using config file: /var/folders/_y/n7114yk15ll_0yps6s3j_v140000gn/T/tmp.cAgWsLNb/launchpad.yaml
   • Loading launchpad settings
      • parsing launchpad config YAML path=/var/folders/_y/n7114yk15ll_0yps6s3j_v140000gn/T/tmp.cAgWsLNb/launchpad.yaml
   • PARSE LAUCHPAD DATABASE
      • found launchpad database  database=/var/folders/_y/n7114yk15ll_0yps6s3j_v140000gn/0/com.apple.dock.launchpad/db/db
         • removed old file          path=/var/folders/_y/n7114yk15ll_0yps6s3j_v140000gn/0/com.apple.dock.launchpad/db/db
         • removed old file          path=/var/folders/_y/n7114yk15ll_0yps6s3j_v140000gn/0/com.apple.dock.launchpad/db/db-shm
         • removed old file          path=/var/folders/_y/n7114yk15ll_0yps6s3j_v140000gn/0/com.apple.dock.launchpad/db/db-wal
      • restarting Dock
      • clear out groups
      • disabling SQL update triggers
      • add root and holding pages
      • creating App folders and adding apps to them
         • found apps/widgets that are not in supplied config count=5
         ...
         • folder added              group=Built-in
         ...
         ...
         ...
         • folder added              group=Other
      • enabling SQL update triggers
      • restarting Dock

> lporg save -V --config ./launchpad.yaml
   • using config file: /var/folders/_y/n7114yk15ll_0yps6s3j_v140000gn/T/tmp.EiKdZGOe/launchpad.yaml
   • Saving launchpad settings
   • SAVING LAUNCHPAD DATABASE
      • found launchpad database  database=/var/folders/_y/n7114yk15ll_0yps6s3j_v140000gn/0/com.apple.dock.launchpad/db/db
   • collecting launchpad/dashboard pages
   • interating over launchpad pages
   • page number: 1
      • found folder              title=Built-in
      ...
      ...
      ...
      • found folder              title=Other
   ⨯ unable to parse launchpad pages: did not find folder page item in page
```
