### ISSUE TITLE
lporg save not correct

### ISSUE THREAD

**Issue by CaptainVincent** [blacktop/lporg#35]
macOS: 13.5.1（22G90）
Version: 20.4.21, BuildTime: 2023-09-04T17:28:18Z
Device: M2

Even though I have many customized folders, but when I run `lporg save`,
I always got below config file. (apple's default app with Chinese name)

```yml
apps:
    pages:
        - number: 1
        - number: 2
          items:
            - App Store
            - 郵件
            - 聯絡人
            - 行事曆
            - 提醒事項
            - 備忘錄
            - FaceTime
            - 訊息
            - 地圖
            - 尋找
            - Photo Booth
            - 照片
            - 預覽程式
            - 音樂
            - Podcast
            - TV
            - 語音備忘錄
            - 天氣
            - 股市
            - 書籍
            - 辭典
            - 計算機
            - 無邊記
            - 家庭
            - folder: 其他
              pages:
                - number: 1
                  items:
                    - Grapher
                    - 旁白工具程式
                    - AirPort工具程式
                    - 系統移轉輔助程式
                    - 終端機
                    - 活動監視器
                    - 系統監視程式
                    - 鑰匙圈存取
                    - 系統資訊
                    - 工序指令編寫程式
                    - 磁碟工具程式
                    - 數位測色計
                    - 色彩同步工具程式
                    - 截圖
                    - 藍牙檔案交換程式
                    - 音訊MIDI設定
widgets:
    pages: []
dock_items:
    apps:
        - /System/Applications/Messages.app
desktop: {}
```
