### ISSUE TITLE
Cannot load config correctly missing apps

### ISSUE THREAD

**Issue by silver886** [blacktop/lporg#46]
In version 20.4.27, it didn't load the config correctly.

It hides all apps that existed, except for Apple's, in the config.
Meanwhile, it only shows icons for apps which are not in the config.

This is the config I tried to load from:
```yaml
apps:
  pages:
    - number: 1
      items:
        - folder: Built-in
          pages:
            - number: 1
              items:
                - App Store
                - Safari
                - Mail
                - Contacts
                - Calendar
                - Reminders
                - Notes
                - FaceTime
                - Messages
                - Maps
                - Find My
                - Photo Booth
                - Photos
                - Preview
                - Music
                - Podcasts
                - TV
                - Voice Memos
                - Stocks
                - Books
                - Dictionary
                - Calculator
                - Home
                - Siri
                - Mission Control
                - System Preferences
        - folder: Toolkit
          pages:
            - number: 1
              items:
                - Shortcuts
                - QuickTime Player
                - TextEdit
                - Grapher
                - Time Machine
                - Font Book
                - Chess
                - Stickies
                - Image Capture
                - VoiceOver Utility
                - AirPort Utility
                - Migration Assistant
                - Terminal
                - Activity Monitor
                - Console
                - Keychain Access
                - System Information
                - Automator
                - Script Editor
                - Disk Utility
                - Boot Camp Assistant
                - Digital Color Meter
                - ColorSync Utility
                - Screenshot
                - Bluetooth File Exchange
                - Audio MIDI Setup
                - Apple Configurator
        - folder: ...
        - folder: ...
        - folder: ...
        - folder: ...
        - folder: ...
        - folder: ...
        - folder: ...
        - folder: ...
        - folder: ...
```

And this is the config I got:
```yaml
apps:
  pages:
    - number: 1
      items:
        - App Store
        - Safari
        - Mail
        - Contacts
        - Calendar
        - Reminders
        - Notes
        - FaceTime
        - Messages
        - Maps
        - Find My
        - Photo Booth
        - Photos
        - Preview
        - Music
        - Podcasts
        - TV
        - Voice Memos
        - GarageBand
        - iMovie
        - Numbers
        - Keynote
        - Pages
        - Stocks
        - Books
        - Dictionary
        - Calculator
        - Home
        - Siri
        - Mission Control
        - System Preferences
        - ...
        - Shortcuts
        - Grapher
        - Time Machine
        - Font Book
        - Stickies
        - VoiceOver Utility
        - AirPort Utility
        - Migration Assistant
        - Terminal
        - Activity Monitor
        - Console
        - Keychain Access
        - System Information
        - Automator
        - Script Editor
        - Disk Utility
        - Boot Camp Assistant
        - Digital Color Meter
        - ColorSync Utility
        - Screenshot
        - Bluetooth File Exchange
        - Audio MIDI Setup
        - TextEdit
        - QuickTime Player
        - Image Capture
    - number: 2
      items:
        - ...
widgets:
  pages: []
dock_items:
  apps:
    - /System/Applications/Launchpad.app
    - /Applications/Safari.app
    - /System/Applications/Messages.app
    - /System/Applications/Mail.app
    - /System/Applications/Maps.app
    - /System/Applications/Photos.app
    - /System/Applications/FaceTime.app
    - /System/Applications/Calendar.app
    - /System/Applications/Contacts.app
    - /System/Applications/Reminders.app
    - /System/Applications/Notes.app
    - /System/Applications/TV.app
    - /System/Applications/Music.app
    - /System/Applications/Podcasts.app
    - /System/Applications/News.app
    - /Applications/Keynote.app
    - /Applications/Numbers.app
    - /Applications/Pages.app
    - /System/Applications/App Store.app
    - /System/Applications/System Preferences.app
  others:
    - path: "~"
      view: 1
      sort: 2
  settings:
    autohide: true
    largesize: 128
    magnification: true
    minimize-to-application: false
    mru-spaces: false
    show-recents: false
    tilesize: 16
desktop: {}
```
