### ISSUE TITLE
Apple apps not respecting order, Other folder keeps appearing

### ISSUE THREAD

**Issue by negebauer** [blacktop/lporg#5]
I have the following Launchpad order

![image](https://user-images.githubusercontent.com/11860880/92515393-ed5a1800-f1e9-11ea-9380-13a5ae75aa9d.png)

Which I save and then load again. After that it looks like this

![image](https://user-images.githubusercontent.com/11860880/92515922-c3552580-f1ea-11ea-8d55-84349cdf4f7d.png)

The Photos, System Preferences and Xcode order is not respected and an Other folder is created (I think it's the default folder where apple apps are placed, when saving the launchpad config again the Other folder is not mentioned). I have to manually order the apps again and add and remove something to the Other folder for it to disappear.

Any ideas what might be happening?

macOS 10.15.6

initial launchpad.yml file

```yml
apps:
  pages:
  - number: 1
    items:
    - folder: .
      pages:
      - number: 1
        items:
        - Hearthstone
        - Hearthstone Beta Launcher
        - editor
    - folder: dock
      pages:
      - number: 1
        items:
        - Calendar
        - HEY
        - Notes
        - Reminders
        - Safari
        - Spark
    - folder: apple
      pages:
      - number: 1
        items:
        - Stocks
        - Mission Control
        - Siri
        - Home
        - Voice Memos
        - TV
        - Photo Booth
        - Calculator
        - Music
        - App Store
        - Podcasts
        - iMovie
        - Mail
        - Maps
        - Preview
        - Bluetooth Explorer
        - Contacts
        - FaceTime
        - Books
        - Numbers
        - Keynote
        - Pages
        - Find My
        - Dictionary
        - Messages
    - folder: apple 2
      pages:
      - number: 1
        items:
        - QuickTime Player
        - TextEdit
        - Grapher
        - Time Machine
        - Font Book
        - Chess
        - Stickies
        - Image Capture
        - VoiceOver Utility
        - AirPort Utility
        - Migration Assistant
        - Terminal
        - Activity Monitor
        - Console
        - Keychain Access
        - System Information
        - Automator
        - Script Editor
        - Disk Utility
        - Boot Camp Assistant
        - Digital Color Meter
        - ColorSync Utility
        - Screenshot
        - Bluetooth File Exchange
        - Audio MIDI Setup
        - XQuartz
    - folder: chat
      pages:
      - number: 1
        items:
        - BlueJeans
        - Discord
        - Skype
        - Slack
        - Telegram
        - Twitter
        - WhatsApp
        - zoom.us
    - Photos
    - Xcode
    - folder: others
      pages:
      - number: 1
        items:
        - Angry IP Scanner
        - DevCleaner
        - Geekbench 4
        - NordVPN IKE
        - Sketch
        - VirtualBox
        - VLC
        - Zeplin
    - folder: utils
      pages:
      - number: 1
        items:
        - Download Shuttle
        - Gifski
        - GrandPerspective
        - HandBrake
        - Image2Icon
        - ImageOptim
        - OnyX
        - KeyboardCleanTool
        - The Unarchiver
        - TimeMachineEditor
        - Transmission
    - folder: dev
      pages:
      - number: 1
        items:
        - Android Studio
        - Docker
        - Google Chrome
        - OpenVPN Connect
        - Postico
        - Postman
        - React Native Debugger
        - Robo 3T
        - Sequel Ace
    - folder: menu bar
      pages:
      - number: 1
        items:
        - Aware
        - Bartender 3
        - CCMenu
        - Dropbox
        - duet
        - Flux
        - Gitify
        - iStat Menus
        - KeepingYouAwake
        - Little Snitch Configuration
        - Micro Snitch
        - MonitorControl
        - Snappy
    - folder: games
      pages:
      - number: 1
        items:
        - Epic Games Launcher
        - Steam
        - barony
        - fate_Generic
        - FTL Faster Than Light
        - Minecraft
        - Pathway
        - The Jackbox Party Pack
    - Spotify
    - 1Password 7
    - MiniPlay
    - System Preferences
    - iTerm
    - Battle.net
    - HSTracker
    - AppCleaner
    - Suspicious Package
    - Visual Studio Code
    - KeyCastr
widgets:
  pages: []
dock_items:
- Launchpad
- Safari
- HEY
- Calendar
- Reminders
- iTerm
- Visual Studio Code
- WhatsApp
- Telegram
- Slack
- Spotify
- Twitter
- ============
- Downloads
- Summit
- Repositories
desktop: {}
```

after loading and saving it again (notice the Other folder is not present)

```yml
apps:
  pages:
  - number: 1
    items:
    - Photos
    - System Preferences
    - Xcode
    - folder: .
      pages:
      - number: 1
        items:
        - Hearthstone
        - Hearthstone Beta Launcher
        - editor
    - folder: dock
      pages:
      - number: 1
        items:
        - Calendar
        - HEY
        - Notes
        - Reminders
        - Safari
        - Spark
    - folder: apple
      pages:
      - number: 1
        items:
        - Stocks
        - Mission Control
        - Siri
        - Home
        - Voice Memos
        - TV
        - Photo Booth
        - Calculator
        - Music
        - App Store
        - Podcasts
        - iMovie
        - Mail
        - Maps
        - Preview
        - Bluetooth Explorer
        - Contacts
        - FaceTime
        - Books
        - Numbers
        - Keynote
        - Pages
        - Find My
        - Dictionary
        - Messages
    - folder: apple 2
      pages:
      - number: 1
        items:
        - QuickTime Player
        - TextEdit
        - Grapher
        - Time Machine
        - Font Book
        - Chess
        - Stickies
        - Image Capture
        - VoiceOver Utility
        - AirPort Utility
        - Migration Assistant
        - Terminal
        - Activity Monitor
        - Console
        - Keychain Access
        - System Information
        - Automator
        - Script Editor
        - Disk Utility
        - Boot Camp Assistant
        - Digital Color Meter
        - ColorSync Utility
        - Screenshot
        - Bluetooth File Exchange
        - Audio MIDI Setup
        - XQuartz
    - folder: chat
      pages:
      - number: 1
        items:
        - BlueJeans
        - Discord
        - Skype
        - Slack
        - Telegram
        - Twitter
        - WhatsApp
        - zoom.us
    - folder: others
      pages:
      - number: 1
        items:
        - Angry IP Scanner
        - DevCleaner
        - Geekbench 4
        - NordVPN IKE
        - Sketch
        - VirtualBox
        - VLC
        - Zeplin
    - folder: utils
      pages:
      - number: 1
        items:
        - Download Shuttle
        - Gifski
        - GrandPerspective
        - HandBrake
        - Image2Icon
        - ImageOptim
        - OnyX
        - KeyboardCleanTool
        - The Unarchiver
        - TimeMachineEditor
        - Transmission
    - folder: dev
      pages:
      - number: 1
        items:
        - Android Studio
        - Docker
        - Google Chrome
        - OpenVPN Connect
        - Postico
        - Postman
        - React Native Debugger
        - Robo 3T
        - Sequel Ace
    - folder: menu bar
      pages:
      - number: 1
        items:
        - Aware
        - Bartender 3
        - CCMenu
        - Dropbox
        - duet
        - Flux
        - Gitify
        - iStat Menus
        - KeepingYouAwake
        - Little Snitch Configuration
        - Micro Snitch
        - MonitorControl
        - Snappy
    - folder: games
      pages:
      - number: 1
        items:
        - Epic Games Launcher
        - Steam
        - barony
        - fate_Generic
        - FTL Faster Than Light
        - Minecraft
        - Pathway
        - The Jackbox Party Pack
    - Spotify
    - 1Password 7
    - MiniPlay
    - iTerm
    - Battle.net
    - HSTracker
    - AppCleaner
    - Suspicious Package
    - Visual Studio Code
    - KeyCastr
widgets:
  pages: []
dock_items:
- Launchpad
- Safari
- HEY
- Calendar
- Reminders
- iTerm
- Visual Studio Code
- WhatsApp
- Telegram
- Slack
- Spotify
- Twitter
- ============
- Downloads
- Summit
- Repositories
desktop: {}
```
